version: '3'
services:
  php:
    image: php:docfony-7.2
    build:
      context: .
      dockerfile: php/Dockerfile
    ports:
      - '9005:9005'
    volumes:
      - '../project:/var/www:cached'
    networks:
      - symfony_dev

  nginx:
    image: nginx:docfony-1.13
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '../project:/var/www:cached'
    networks:
      - symfony_dev

  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - 'dev-mysql:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: "${MYSQL_DB_NAME}"
      MYSQL_USER: "${MYSQL_USR}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "${MYSQL_EMPTY_PWD}"
    networks:
      - symfony_dev

  mongo:
      image: mongo:3.4
      ports:
        - '27017:27017'
      volumes:
        - 'dev-mongo:/data/db'
        - 'dev-mongo-config:/data/configdb'
      networks:
        - symfony_dev

networks:
  symfony_dev:
    driver: bridge

volumes:
  dev-mysql:
  dev-mongo:
  dev-mongo-config: