version: '3'
services:
  php:
    image: php:docfony-dev-7.2
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - '../project:/var/www'
    networks:
      - symfony_dev

  nginx:
    image: nginx:docfony-dev-1.13
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '../project:/var/www'
    networks:
      - symfony_dev

  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - 'dev-mysql:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: 'symfony'
      MYSQL_USER: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - symfony_dev

  mongo:
      image: mongo:3.4
      ports:
        - '27017:27017'
      volumes:
        - 'dev-mongo:/data'
      networks:
        - symfony_dev

networks:
  symfony_dev:
    driver: bridge

volumes:
  dev-mysql:
  dev-mongo: